export const defaultLayouts = {
  lg: [
    {
      i: "workout-features",
      x: 0,
      y: 19,
      w: 2,
      h: 12,
      minW: 2,
      maxW: 6,
      minH: 10,
      maxH: 16,
    },
    {
      i: "status",
      x: 0,
      y: 0,
      w: 2,
      h: 5,
      minW: 1,
      maxW: 6,
      minH: 3,
      maxH: 10,
    },
    { i: "train", x: 0, y: 5, w: 2, h: 7, minW: 1, maxW: 6, minH: 3, maxH: 12 },
    { i: "rest", x: 0, y: 12, w: 2, h: 7, minW: 1, maxW: 6, minH: 3, maxH: 12 },
    {
      i: "workout-logs",
      x: 2,
      y: 0,
      w: 6,
      h: 18,
      minW: 3,
      maxW: 8,
      minH: 8,
      maxH: 24,
    },
    {
      i: "muscle-distribution",
      x: 8,
      y: 0,
      w: 4,
      h: 15,
      minW: 2,
      maxW: 6,
      minH: 6,
      maxH: 20,
    },
    {
      i: "workout-count",
      x: 8,
      y: 15,
      w: 2,
      h: 5,
      minW: 1,
      maxW: 4,
      minH: 3,
      maxH: 8,
    },
    {
      i: "total-volume",
      x: 10,
      y: 15,
      w: 2,
      h: 5,
      minW: 1,
      maxW: 4,
      minH: 3,
      maxH: 8,
    },
    {
      i: "todo-list",
      x: 8,
      y: 20,
      w: 4,
      h: 18,
      minW: 2,
      maxW: 6,
      minH: 8,
      maxH: 24,
    },
    {
      i: "workout-summary",
      x: 0,
      y: 19,
      w: 12,
      h: 18,
      minW: 4,
      maxW: 12,
      minH: 8,
      maxH: 24,
    },
    {
      i: "progression-fatigue",
      x: 0,
      y: 37,
      w: 3,
      h: 15,
      minW: 2,
      maxW: 6,
      minH: 6,
      maxH: 20,
    },
    {
      i: "progression-muscle",
      x: 3,
      y: 37,
      w: 3,
      h: 15,
      minW: 2,
      maxW: 6,
      minH: 6,
      maxH: 20,
    },
    {
      i: "volume-over-time",
      x: 6,
      y: 37,
      w: 3,
      h: 15,
      minW: 2,
      maxW: 6,
      minH: 6,
      maxH: 20,
    },
    {
      i: "fatigue-by-muscle",
      x: 9,
      y: 37,
      w: 3,
      h: 15,
      minW: 2,
      maxW: 6,
      minH: 6,
      maxH: 20,
    },
    {
      i: "progress-goals",
      x: 0,
      y: 52,
      w: 6,
      h: 12,
      minW: 3,
      maxW: 8,
      minH: 6,
      maxH: 16,
    },
    {
      i: "body-weight",
      x: 0,
      y: 64,
      w: 6,
      h: 10,
      minW: 3,
      maxW: 8,
      minH: 4,
      maxH: 14,
    },
    {
      i: "achievements",
      x: 6,
      y: 52,
      w: 6,
      h: 14,
      minW: 3,
      maxW: 8,
      minH: 6,
      maxH: 18,
    },
    {
      i: "weekly-summary",
      x: 0,
      y: 74,
      w: 6,
      h: 14,
      minW: 3,
      maxW: 8,
      minH: 6,
      maxH: 18,
    },
    {
      i: "monthly-summary",
      x: 6,
      y: 74,
      w: 6,
      h: 14,
      minW: 3,
      maxW: 8,
      minH: 6,
      maxH: 18,
    },
    {
      i: "streak-tracker",
      x: 0,
      y: 88,
      w: 6,
      h: 14,
      minW: 3,
      maxW: 8,
      minH: 6,
      maxH: 18,
    },
  ],
  md: [
    {
      i: "workout-features",
      x: 4,
      y: 24,
      w: 4,
      h: 12,
      minW: 2,
      maxW: 6,
      minH: 10,
      maxH: 16,
    },
    {
      i: "status",
      x: 0,
      y: 0,
      w: 3,
      h: 5,
      minW: 1,
      maxW: 6,
      minH: 3,
      maxH: 10,
    },
    { i: "train", x: 0, y: 5, w: 3, h: 7, minW: 1, maxW: 6, minH: 3, maxH: 12 },
    { i: "rest", x: 0, y: 12, w: 3, h: 7, minW: 1, maxW: 6, minH: 3, maxH: 12 },
    {
      i: "workout-logs",
      x: 3,
      y: 0,
      w: 6,
      h: 18,
      minW: 3,
      maxW: 9,
      minH: 8,
      maxH: 24,
    },
    {
      i: "muscle-distribution",
      x: 0,
      y: 18,
      w: 4,
      h: 15,
      minW: 2,
      maxW: 6,
      minH: 6,
      maxH: 20,
    },
    {
      i: "workout-count",
      x: 4,
      y: 18,
      w: 2,
      h: 5,
      minW: 1,
      maxW: 4,
      minH: 3,
      maxH: 8,
    },
    {
      i: "total-volume",
      x: 6,
      y: 18,
      w: 2,
      h: 5,
      minW: 1,
      maxW: 4,
      minH: 3,
      maxH: 8,
    },
    {
      i: "todo-list",
      x: 0,
      y: 33,
      w: 4,
      h: 18,
      minW: 2,
      maxW: 6,
      minH: 8,
      maxH: 24,
    },
    {
      i: "workout-summary",
      x: 0,
      y: 51,
      w: 9,
      h: 18,
      minW: 4,
      maxW: 9,
      minH: 8,
      maxH: 24,
    },
    {
      i: "progression-fatigue",
      x: 0,
      y: 69,
      w: 3,
      h: 15,
      minW: 2,
      maxW: 6,
      minH: 6,
      maxH: 20,
    },
    {
      i: "progression-muscle",
      x: 3,
      y: 69,
      w: 3,
      h: 15,
      minW: 2,
      maxW: 6,
      minH: 6,
      maxH: 20,
    },
    {
      i: "volume-over-time",
      x: 6,
      y: 69,
      w: 3,
      h: 15,
      minW: 2,
      maxW: 6,
      minH: 6,
      maxH: 20,
    },
    {
      i: "fatigue-by-muscle",
      x: 0,
      y: 84,
      w: 3,
      h: 15,
      minW: 2,
      maxW: 6,
      minH: 6,
      maxH: 20,
    },
    {
      i: "progress-goals",
      x: 0,
      y: 99,
      w: 4,
      h: 12,
      minW: 3,
      maxW: 6,
      minH: 6,
      maxH: 16,
    },
    {
      i: "body-weight",
      x: 4,
      y: 99,
      w: 4,
      h: 10,
      minW: 3,
      maxW: 6,
      minH: 4,
      maxH: 14,
    },
    {
      i: "achievements",
      x: 0,
      y: 109,
      w: 4,
      h: 14,
      minW: 3,
      maxW: 6,
      minH: 6,
      maxH: 18,
    },
    {
      i: "weekly-summary",
      x: 0,
      y: 123,
      w: 4,
      h: 14,
      minW: 3,
      maxW: 6,
      minH: 6,
      maxH: 18,
    },
    {
      i: "monthly-summary",
      x: 4,
      y: 123,
      w: 4,
      h: 14,
      minW: 3,
      maxW: 6,
      minH: 6,
      maxH: 18,
    },
    {
      i: "streak-tracker",
      x: 0,
      y: 137,
      w: 4,
      h: 14,
      minW: 3,
      maxW: 6,
      minH: 6,
      maxH: 18,
    },
  ],
  sm: [
    {
      i: "workout-features",
      x: 0,
      y: 19,
      w: 6,
      h: 12,
      minW: 3,
      maxW: 6,
      minH: 10,
      maxH: 16,
    },
    {
      i: "status",
      x: 0,
      y: 0,
      w: 6,
      h: 5,
      minW: 3,
      maxW: 6,
      minH: 3,
      maxH: 10,
    },
    { i: "train", x: 0, y: 5, w: 6, h: 7, minW: 3, maxW: 6, minH: 3, maxH: 12 },
    { i: "rest", x: 0, y: 12, w: 6, h: 7, minW: 3, maxW: 6, minH: 3, maxH: 12 },
    {
      i: "workout-logs",
      x: 0,
      y: 19,
      w: 6,
      h: 18,
      minW: 4,
      maxW: 6,
      minH: 8,
      maxH: 24,
    },
    {
      i: "muscle-distribution",
      x: 0,
      y: 37,
      w: 6,
      h: 15,
      minW: 4,
      maxW: 6,
      minH: 6,
      maxH: 20,
    },
    {
      i: "workout-count",
      x: 0,
      y: 52,
      w: 3,
      h: 5,
      minW: 3,
      maxW: 6,
      minH: 3,
      maxH: 8,
    },
    {
      i: "total-volume",
      x: 3,
      y: 52,
      w: 3,
      h: 5,
      minW: 3,
      maxW: 6,
      minH: 3,
      maxH: 8,
    },
    {
      i: "todo-list",
      x: 0,
      y: 57,
      w: 6,
      h: 18,
      minW: 4,
      maxW: 6,
      minH: 8,
      maxH: 24,
    },
    {
      i: "workout-summary",
      x: 0,
      y: 75,
      w: 6,
      h: 18,
      minW: 4,
      maxW: 6,
      minH: 8,
      maxH: 24,
    },
    {
      i: "progression-fatigue",
      x: 0,
      y: 93,
      w: 6,
      h: 15,
      minW: 4,
      maxW: 6,
      minH: 6,
      maxH: 20,
    },
    {
      i: "progression-muscle",
      x: 0,
      y: 108,
      w: 6,
      h: 15,
      minW: 4,
      maxW: 6,
      minH: 6,
      maxH: 20,
    },
    {
      i: "volume-over-time",
      x: 0,
      y: 123,
      w: 6,
      h: 15,
      minW: 4,
      maxW: 6,
      minH: 6,
      maxH: 20,
    },
    {
      i: "fatigue-by-muscle",
      x: 0,
      y: 138,
      w: 6,
      h: 15,
      minW: 4,
      maxW: 6,
      minH: 6,
      maxH: 20,
    },
    {
      i: "progress-goals",
      x: 0,
      y: 153,
      w: 6,
      h: 12,
      minW: 4,
      maxW: 6,
      minH: 6,
      maxH: 16,
    },
    {
      i: "body-weight",
      x: 0,
      y: 165,
      w: 6,
      h: 10,
      minW: 4,
      maxW: 6,
      minH: 4,
      maxH: 14,
    },
    {
      i: "achievements",
      x: 0,
      y: 175,
      w: 6,
      h: 14,
      minW: 4,
      maxW: 6,
      minH: 6,
      maxH: 18,
    },
    {
      i: "weekly-summary",
      x: 0,
      y: 189,
      w: 6,
      h: 14,
      minW: 4,
      maxW: 6,
      minH: 6,
      maxH: 18,
    },
    {
      i: "monthly-summary",
      x: 0,
      y: 203,
      w: 6,
      h: 14,
      minW: 4,
      maxW: 6,
      minH: 6,
      maxH: 18,
    },
    {
      i: "streak-tracker",
      x: 0,
      y: 217,
      w: 6,
      h: 14,
      minW: 4,
      maxW: 6,
      minH: 6,
      maxH: 18,
    },
  ],
  xs: [
    {
      i: "workout-features",
      x: 0,
      y: 8,
      w: 4,
      h: 10,
      minW: 2,
      maxW: 4,
      minH: 8,
      maxH: 14,
    },
    {
      i: "status",
      x: 0,
      y: 0,
      w: 2,
      h: 4,
      minW: 1,
      maxW: 4,
      minH: 3,
      maxH: 6,
    },
    { i: "train", x: 2, y: 0, w: 2, h: 4, minW: 1, maxW: 4, minH: 3, maxH: 6 },
    { i: "rest", x: 0, y: 4, w: 2, h: 4, minW: 1, maxW: 4, minH: 3, maxH: 6 },
    { i: "workout-count", x: 2, y: 4, w: 2, h: 4, minW: 1, maxW: 4, minH: 3, maxH: 6 },
    {
      i: "total-volume",
      x: 0,
      y: 8,
      w: 4,
      h: 4,
      minW: 2,
      maxW: 4,
      minH: 3,
      maxH: 6,
    },
    {
      i: "todo-list",
      x: 0,
      y: 12,
      w: 4,
      h: 12,
      minW: 2,
      maxW: 4,
      minH: 6,
      maxH: 16,
    },
    {
      i: "workout-logs",
      x: 0,
      y: 24,
      w: 4,
      h: 16,
      minW: 2,
      maxW: 4,
      minH: 6,
      maxH: 20,
    },
    {
      i: "muscle-distribution",
      x: 0,
      y: 40,
      w: 4,
      h: 15,
      minW: 2,
      maxW: 4,
      minH: 6,
      maxH: 20,
    },
    {
      i: "workout-summary",
      x: 0,
      y: 55,
      w: 4,
      h: 16,
      minW: 2,
      maxW: 4,
      minH: 6,
      maxH: 20,
    },
    {
      i: "progression-fatigue",
      x: 0,
      y: 71,
      w: 4,
      h: 14,
      minW: 2,
      maxW: 4,
      minH: 6,
      maxH: 18,
    },
    {
      i: "progression-muscle",
      x: 0,
      y: 85,
      w: 4,
      h: 14,
      minW: 2,
      maxW: 4,
      minH: 6,
      maxH: 18,
    },
    {
      i: "volume-over-time",
      x: 0,
      y: 99,
      w: 4,
      h: 14,
      minW: 2,
      maxW: 4,
      minH: 6,
      maxH: 18,
    },
    {
      i: "fatigue-by-muscle",
      x: 0,
      y: 113,
      w: 4,
      h: 14,
      minW: 2,
      maxW: 4,
      minH: 6,
      maxH: 18,
    },
    {
      i: "progress-goals",
      x: 0,
      y: 127,
      w: 4,
      h: 12,
      minW: 2,
      maxW: 4,
      minH: 6,
      maxH: 16,
    },
    {
      i: "body-weight",
      x: 0,
      y: 139,
      w: 4,
      h: 10,
      minW: 2,
      maxW: 4,
      minH: 4,
      maxH: 14,
    },
    {
      i: "achievements",
      x: 0,
      y: 149,
      w: 4,
      h: 14,
      minW: 2,
      maxW: 4,
      minH: 6,
      maxH: 18,
    },
    {
      i: "weekly-summary",
      x: 0,
      y: 163,
      w: 4,
      h: 14,
      minW: 2,
      maxW: 4,
      minH: 6,
      maxH: 18,
    },
    {
      i: "monthly-summary",
      x: 0,
      y: 177,
      w: 4,
      h: 14,
      minW: 2,
      maxW: 4,
      minH: 6,
      maxH: 18,
    },
    {
      i: "streak-tracker",
      x: 0,
      y: 191,
      w: 4,
      h: 14,
      minW: 2,
      maxW: 4,
      minH: 6,
      maxH: 18,
    },
  ],
};

export const getRecentWorkoutLogs = (logs) => {
  if (!logs || logs.length === 0) return [];
  return logs
    .slice(-3)
    .map((log) => {
      const weight = log[4] === 0 ? "Bodyweight" : log[4];
      return {
        date: log[0],
        muscleGroup: log[1],
        exercise: log[2],
        reps: log[3],
        weight,
        rating: log[5],
      };
    })
    .reverse();
};